[programs.localnet]
messengerapp = "8nJ2eyGcQ7hVdqLrr9XyiqADc9a4C2f67SSaG2WtL9Pu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/rustam/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
